/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author dell
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double NumEnter1 ; 
    double NumEnter2 ; 
    double Result ; 
    String op ; 

    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        JtxtResult = new javax.swing.JTextField();
        JbtnCE = new javax.swing.JButton();
        JbtnBS = new javax.swing.JButton();
        JbtnClear = new javax.swing.JButton();
        JbtnPM = new javax.swing.JButton();
        JbtnPlus = new javax.swing.JButton();
        JbtnDijit9 = new javax.swing.JButton();
        JbtnDijit8 = new javax.swing.JButton();
        JbtnDijit7 = new javax.swing.JButton();
        JbtnMinus = new javax.swing.JButton();
        JbtnDijit6 = new javax.swing.JButton();
        JbtnDijit5 = new javax.swing.JButton();
        JbtnDijit4 = new javax.swing.JButton();
        JbtnMulti = new javax.swing.JButton();
        JbtnDijit3 = new javax.swing.JButton();
        JbtnDijit2 = new javax.swing.JButton();
        JbtnDijit1 = new javax.swing.JButton();
        JbtnDivi = new javax.swing.JButton();
        JbtnEqual = new javax.swing.JButton();
        JbtnPoint = new javax.swing.JButton();
        JbtnDijit0 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JtxtResult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(JtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 50));

        JbtnCE.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnCE.setText("CE");
        JbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 74, 60));

        JbtnBS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnBS.setText("Del");
        JbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 74, 60));

        JbtnClear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnClear.setText("C");
        JbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 74, 60));

        JbtnPM.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnPM.setText("±");
        JbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 74, 60));

        JbtnPlus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnPlus.setText("+");
        JbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 74, 60));

        JbtnDijit9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit9.setText("9");
        JbtnDijit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit9ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 74, 60));

        JbtnDijit8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit8.setText("8");
        JbtnDijit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit8ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 74, 60));

        JbtnDijit7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit7.setText("7");
        JbtnDijit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit7ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 74, 60));

        JbtnMinus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnMinus.setText("-");
        JbtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 74, 60));

        JbtnDijit6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit6.setText("6");
        JbtnDijit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit6ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 74, 60));

        JbtnDijit5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit5.setText("5");
        JbtnDijit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit5ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 74, 60));

        JbtnDijit4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit4.setText("4");
        JbtnDijit4.setToolTipText("");
        JbtnDijit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit4ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 74, 60));

        JbtnMulti.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnMulti.setText("*");
        JbtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnMultiActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 74, 60));

        JbtnDijit3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit3.setText("3");
        JbtnDijit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit3ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 74, 60));

        JbtnDijit2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit2.setText("2");
        JbtnDijit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit2ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 74, 60));

        JbtnDijit1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit1.setText("1");
        JbtnDijit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit1ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 74, 60));

        JbtnDivi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDivi.setText("/");
        JbtnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDiviActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 74, 60));

        JbtnEqual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnEqual.setText("=");
        JbtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnEqualActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 74, 60));

        JbtnPoint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnPoint.setText(".");
        JbtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPointActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 74, 60));

        JbtnDijit0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnDijit0.setText("0");
        JbtnDijit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDijit0ActionPerformed(evt);
            }
        });
        getContentPane().add(JbtnDijit0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 74, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnDijit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit7ActionPerformed
     EnterNumbers("7") ; 
    }//GEN-LAST:event_JbtnDijit7ActionPerformed

    private void JbtnDijit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit8ActionPerformed
EnterNumbers("8") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit8ActionPerformed

    private void JbtnDijit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit9ActionPerformed
EnterNumbers("9") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit9ActionPerformed

    private void JbtnDijit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit4ActionPerformed
EnterNumbers("4") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit4ActionPerformed

    private void JbtnDijit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit5ActionPerformed
EnterNumbers("5") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit5ActionPerformed

    private void JbtnDijit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit6ActionPerformed
EnterNumbers("6") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit6ActionPerformed

    private void JbtnDijit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit1ActionPerformed
EnterNumbers("1") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit1ActionPerformed

    private void JbtnDijit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit2ActionPerformed
EnterNumbers("2") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit2ActionPerformed

    private void JbtnDijit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit3ActionPerformed
EnterNumbers("3") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit3ActionPerformed

    private void JbtnDijit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDijit0ActionPerformed
EnterNumbers("0") ;         // TODO add your handling code here:
    }//GEN-LAST:event_JbtnDijit0ActionPerformed

    private void JbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDiviActionPerformed
      NumEnter1 = Double.parseDouble(JtxtResult.getText()) ; 
      JtxtResult.setText("");
      op ="/" ; 
    }//GEN-LAST:event_JbtnDiviActionPerformed

    private void JbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnMultiActionPerformed
     NumEnter1 = Double.parseDouble(JtxtResult.getText()) ; 
      JtxtResult.setText("");
      op ="*" ; 
    }//GEN-LAST:event_JbtnMultiActionPerformed

    private void JbtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnMinusActionPerformed
      NumEnter1 = Double.parseDouble(JtxtResult.getText()) ; 
      JtxtResult.setText("");
      op ="-" ; 
    }//GEN-LAST:event_JbtnMinusActionPerformed

    private void JbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPlusActionPerformed
    NumEnter1 = Double.parseDouble(JtxtResult.getText()) ; 
      JtxtResult.setText("");
      op ="+" ; 
    }//GEN-LAST:event_JbtnPlusActionPerformed

    private void JbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnClearActionPerformed
      JtxtResult.setText("");
    }//GEN-LAST:event_JbtnClearActionPerformed

    private void JbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCEActionPerformed
     JtxtResult.setText("");
     String Fn , Sn ; 
     Fn = String.valueOf(NumEnter1) ;
     Sn = String.valueOf(NumEnter2) ;
     Fn = "" ; 
     Sn ="" ; 
     
    }//GEN-LAST:event_JbtnCEActionPerformed

    private void JbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPMActionPerformed
    double nums = Double.parseDouble(String.valueOf(JtxtResult.getText()));
     nums = nums * (-1) ; 
     JtxtResult.setText(String.valueOf(nums));
    }//GEN-LAST:event_JbtnPMActionPerformed

    private void JbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBSActionPerformed
      String backSp = null ;
      if(JtxtResult.getText().length() > 0){
          StringBuilder sb = new StringBuilder(JtxtResult.getText()) ;
          sb.deleteCharAt(JtxtResult.getText().length() - 1) ; 
          backSp = sb.toString() ; 
          JtxtResult.setText(backSp) ; 
      }
    }//GEN-LAST:event_JbtnBSActionPerformed

    private void JbtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPointActionPerformed
    if(! JtxtResult.getText().contains(".")){
        JtxtResult.setText(JtxtResult.getText() + JbtnPoint.getText());
    }
    }//GEN-LAST:event_JbtnPointActionPerformed

    private void JbtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnEqualActionPerformed
    NumEnter2 = Double.parseDouble(JtxtResult.getText()) ; 
    if(op== "+"){
        Result = NumEnter1 + NumEnter2 ; 
        JtxtResult.setText(String.valueOf(Result)) ; 
    }
    else if(op == "-"){
        Result = NumEnter1 - NumEnter2 ; 
        JtxtResult.setText(String.valueOf(Result)) ; 
    }
    else if(op =="*"){
        Result = NumEnter1 * NumEnter2 ; 
        JtxtResult.setText(String.valueOf(Result)) ; 
    }
    else if(op=="/"){
        Result = NumEnter1 / NumEnter2 ; 
        if(NumEnter2 == 0){
            JtxtResult.setText("Impossible");
        }
        else{
            JtxtResult.setText(String.valueOf(Result)) ;
        }
         
    }
    }//GEN-LAST:event_JbtnEqualActionPerformed

    private void EnterNumbers(String q)
    {
        String Nums = JtxtResult.getText() + q ; 
        JtxtResult.setText(Nums);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnBS;
    private javax.swing.JButton JbtnCE;
    private javax.swing.JButton JbtnClear;
    private javax.swing.JButton JbtnDijit0;
    private javax.swing.JButton JbtnDijit1;
    private javax.swing.JButton JbtnDijit2;
    private javax.swing.JButton JbtnDijit3;
    private javax.swing.JButton JbtnDijit4;
    private javax.swing.JButton JbtnDijit5;
    private javax.swing.JButton JbtnDijit6;
    private javax.swing.JButton JbtnDijit7;
    private javax.swing.JButton JbtnDijit8;
    private javax.swing.JButton JbtnDijit9;
    private javax.swing.JButton JbtnDivi;
    private javax.swing.JButton JbtnEqual;
    private javax.swing.JButton JbtnMinus;
    private javax.swing.JButton JbtnMulti;
    private javax.swing.JButton JbtnPM;
    private javax.swing.JButton JbtnPlus;
    private javax.swing.JButton JbtnPoint;
    private javax.swing.JTextField JtxtResult;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
