package Elevator;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.BlockingQueue ;
import java.util.concurrent.LinkedBlockingQueue ; 

/**
 *
 * @author Dell
 */
public class Elevator extends javax.swing.JFrame {
    
    private Timer timer ; 
    int currentFloor = 0 ; 
    private final int FLOOR_HEIGHT = 100 ; 
    private final int NUM_FLOOR = 6 ;
    private final int DELAY = 1000 ; 
    private final BlockingQueue<Integer> floorRequests = new LinkedBlockingQueue<>();
    private final int STOP_DELAY = 3000;
    private boolean isMoving = false;
    
    
    
    public Elevator() {
        initComponents();
    }
    
    private void moveElevator() {
        if (!floorRequests.isEmpty()) {
            isMoving = true;
            final int destinationFloor = floorRequests.poll();
            final int newY = 500 - destinationFloor * FLOOR_HEIGHT;
            final int currentY = ElevatorSimulation.getY();
            final int deltaY = (newY - currentY) / 20;

            Thread moveThread = new Thread(() -> {
                try {
                    for (int frameCount = 0; frameCount < 20; frameCount++) {
                        SwingUtilities.invokeLater(() -> ElevatorSimulation.setLocation(ElevatorSimulation.getX(), ElevatorSimulation.getY() + deltaY));
                        Thread.sleep(DELAY);
                    }
                    currentFloor = destinationFloor;
                    if (destinationFloor != 0) {
                        stopAtFloor();
                    } else {
                        isMoving = false;
                        if (!floorRequests.isEmpty()) {
                            moveElevator();
                        }
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            });

            moveThread.start();
        }
    }



    private void stopAtFloor() {
        Thread stopThread = new Thread(() -> {
            try {
                Thread.sleep(STOP_DELAY);
                isMoving = false;
                if (!floorRequests.isEmpty()) {
                    moveElevator();
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        });

        stopThread.start();
    }


    private void handleFloorRequest(int floor) {
        floorRequests.add(floor);
        if (!isMoving) {
            moveElevator();
        }
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        ElevatorTitle = new javax.swing.JLabel();
        Jbtn1Floor = new javax.swing.JButton();
        Jbtn2Floor = new javax.swing.JButton();
        Jbtn3Floor = new javax.swing.JButton();
        Jbtn4Floor = new javax.swing.JButton();
        Jbtn6Floor = new javax.swing.JButton();
        Jbtn5Floor = new javax.swing.JButton();
        JtitleFloors = new javax.swing.JLabel();
        ElevatorFile = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ElevatorSimulation = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ElevatorTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        ElevatorTitle.setText("Elevator Simulation ");
        getContentPane().add(ElevatorTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        Jbtn1Floor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbtn1Floor.setText("G Floor");
        Jbtn1Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn1FloorActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn1Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        Jbtn2Floor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbtn2Floor.setText("1th");
        Jbtn2Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn2FloorActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn2Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        Jbtn3Floor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbtn3Floor.setText("2th");
        Jbtn3Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn3FloorActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn3Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        Jbtn4Floor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbtn4Floor.setText("3th");
        Jbtn4Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn4FloorActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn4Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        Jbtn6Floor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbtn6Floor.setText("5th");
        Jbtn6Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn6FloorActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn6Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        Jbtn5Floor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Jbtn5Floor.setText("4th");
        Jbtn5Floor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn5FloorActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn5Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        JtitleFloors.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        JtitleFloors.setText("Set the Floor : ");
        getContentPane().add(JtitleFloors, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        ElevatorFile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(ElevatorFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 90, 740));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("2th");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("3th");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("4th");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("5th");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText(" G Floor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("1th");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        ElevatorSimulation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/elevator (1).png"))); // NOI18N
        getContentPane().add(ElevatorSimulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 130, 150));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 30, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn1FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn1FloorActionPerformed

        handleFloorRequest(0);
    }//GEN-LAST:event_Jbtn1FloorActionPerformed

    private void Jbtn2FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn2FloorActionPerformed
      
                handleFloorRequest(1);
    }//GEN-LAST:event_Jbtn2FloorActionPerformed

    private void Jbtn3FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn3FloorActionPerformed
       
                handleFloorRequest(2);
        
    }//GEN-LAST:event_Jbtn3FloorActionPerformed

    private void Jbtn4FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn4FloorActionPerformed
    
                handleFloorRequest(3);


    }//GEN-LAST:event_Jbtn4FloorActionPerformed

    private void Jbtn5FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn5FloorActionPerformed
      
                handleFloorRequest(4);
    }//GEN-LAST:event_Jbtn5FloorActionPerformed

    private void Jbtn6FloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn6FloorActionPerformed
       
                handleFloorRequest(5);
    }//GEN-LAST:event_Jbtn6FloorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Elevator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Elevator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler ElevatorFile;
    private javax.swing.JLabel ElevatorSimulation;
    private javax.swing.JLabel ElevatorTitle;
    private javax.swing.JButton Jbtn1Floor;
    private javax.swing.JButton Jbtn2Floor;
    private javax.swing.JButton Jbtn3Floor;
    private javax.swing.JButton Jbtn4Floor;
    private javax.swing.JButton Jbtn5Floor;
    private javax.swing.JButton Jbtn6Floor;
    private javax.swing.JLabel JtitleFloors;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables

}






